import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main tutorial sidebar - includes root docs and tutorial-basics
  tutorialSidebar: [
    'intro',
    'QR Codes The Invisible Backbone of Modern China',
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'},
  ],

  // Cities section sidebar
  citiesSidebar: [{type: 'autogenerated', dirName: 'cities'}],

  // Universities section sidebar
  universitiesSidebar: [{type: 'autogenerated', dirName: 'universities'}],

  // Local Services section sidebar
  localServicesSidebar: [{type: 'autogenerated', dirName: 'local-services'}],
};

export default sidebars;
